// Question of the Day pool. Sprout walks through it in order (it's already
// mixed up), then starts over. Staff can queue their own with `!qotd add`,
// which always go first. Add as many as you like.

export const questions: readonly string[] = [
  "What's a small thing that made you happy this week?",
  "If you could instantly master one skill, what would it be?",
  "What's the best thing you've eaten recently?",
  "Which game could you replay forever?",
  "What's a song you never skip?",
  "What's your go-to comfort movie or show?",
  "If you could live in any fictional world, which one would you pick?",
  "What's something you're looking forward to?",
  "Cats, dogs, or something way more interesting?",
  "What's the most useful thing you own?",
  "What hobby would you pick up if time and money were no object?",
  "What's a hill you're willing to die on?",
  "What did you want to be when you grew up?",
  "What's the best piece of advice you've ever been given?",
  "Describe your perfect lazy Sunday.",
  "What's a book, show or game you think is criminally underrated?",
  "Morning person or night owl?",
  "What's a skill you have that most people don't know about?",
  "If you had a theme song that played when you walked into a room, what would it be?",
  "What's the last thing you made, built or created?",
  "What's your favorite smell?",
  "What's the weirdest food combination you secretly love?",
  "Which video game soundtrack lives rent-free in your head?",
  "If you could have dinner with any three people (real or fictional), who would they be?",
  "What's one thing on your bucket list?",
  "What's your favorite season and why?",
  "What app do you use the most that isn't social media?",
  "What's a movie you can quote by heart?",
  "Sweet or savory breakfast?",
  "What's the best concert or live event you've been to?",
  "What would your superpower be, and what would you actually use it for?",
  "What's a tiny habit that improved your life?",
  "What's the most beautiful place you've ever been?",
  "Which fictional character do you relate to the most?",
  "What's something you changed your mind about in the last few years?",
  "If you opened a shop, what would it sell?",
  "What's your favorite board game or card game?",
  "What's your current desktop or phone wallpaper?",
  "What's a game you were way too good at as a kid?",
  "What's the best gift you've ever received?",
  "Pineapple on pizza: yes or no? Defend your answer.",
  "What's a word you love the sound of?",
  "What would you name a pet dragon?",
  "What's something you're proud of but rarely get to talk about?",
  "What's your favorite way to unwind after a long day?",
  "Which three apps would you keep if you could only have three?",
  "What's a trend you just don't get?",
  "If you could time-travel once, past or future?",
  "What's the best thing about where you live?",
  "What did you learn recently that blew your mind?",
  "What's your all-time favorite snack?",
  "What's a show you'd love to watch again for the first time?",
  "What's your most controversial food opinion?",
  "If animals could talk, which would be the rudest?",
  "What's your favorite thing about this community so far?",
  "What's an outfit or item of clothing you'll never give up?",
  "What's a game mechanic you wish more games had?",
  "Coffee, tea, or something else entirely?",
  "What's the strangest dream you remember?",
  "What's a place you've always wanted to visit?",
  "What's your favorite holiday tradition?",
  "If you could rename yourself, what name would you pick?",
  "What's the last thing that made you laugh out loud?",
  "What's a fun fact you love telling people?",
  "What's your favorite piece of art, in any medium?",
  "What's one thing you'd teach everyone in the world if you could?",
  "What's the most unusual job you've had or heard of?",
  "What's your ideal road trip snack lineup?",
  "If your life were a video game, what would the loading screen tips say?",
  "Which decade's music is the best?",
  "What's something you collect, or used to?",
  "What's your favorite thing to cook or bake?",
  "Which game world would you NOT want to live in?",
  "What would you do with a free day tomorrow?",
  "What's your favorite kind of weather?",
  "What's the best plot twist you've ever seen?",
  "If you could only eat one cuisine for the rest of your life, which would it be?",
  "What's a small act of kindness you'll never forget?",
  "What's a skill you're learning right now?",
  "What's the best YouTube channel or podcast you've found recently?",
  "Would you rather explore the deep sea or outer space?",
  "What's an underrated feature of your favorite city?",
  "What's your favorite emoji, and how do you use it?",
  "What's a song that instantly takes you back to a specific moment?",
  "If you could add one thing to this community, what would it be?",
  "What's a childhood show you'd still watch today?",
  "What's your go-to karaoke song?",
  "What's the best thing you've bought for under $20?",
  "Which fictional food do you wish you could try?",
  "What's your favorite quote?",
  "What's your secret talent in the kitchen?",
  "If you could swap lives with someone for a day, who would it be?",
  "What's a game you'd recommend to someone who doesn't play games?",
  "What's a tradition from your family or culture you love?",
  "What's your favorite animal and why?",
  "What's the best compliment you've ever received?",
  "What's the first thing you'd buy if you won the lottery?",
  "What's your favorite font? (Yes, you have one.)",
  "What movie or game would you love to see a sequel to?",
  "What's a goal you're working towards this year?",
  "What's your favorite thing to do with friends?",
  "Which mythical creature would make the best pet?",
  "What's something that always cheers you up?",
  "What's the most interesting thing within arm's reach right now?",
  "What's your favorite sound?",
  "Which game, show or book character would be your best friend?",
  "What's an opinion you have that most people would disagree with?",
  "What's your favorite memory from this year so far?",
  "If you had to teach a class on anything, what would it be?",
  "What's your favorite late-night activity?",
  "What's a dish from another country everyone should try?",
  "What's the coziest place you know?",
  "What would be the title of your autobiography?",
  "What's a recent win, big or small, you want to celebrate?",
  "What's a question you wish people asked you more often?",
];
